
#' As Data Tree
#' @description Converts a data.frame generated by a get_ function into a hierarchy using [data.tree::as.Node()].
#' @param structure A data.frame with labelled
#' @param type character, one of
#'  - `code` a data tree with levelNames based on hierarchy codes
#'  - `desc` a data tree with levelNames based on hierarchy code descriptions
#' @returns An option of class `data.tree`
#' @export
#' @importFrom dplyr mutate across all_of
#' @importFrom rlang syms
#' @importFrom labelled to_character
#' @importFrom data.tree as.Node

as_datatree <- function(structure,
                        type=c("code", "desc")) {
  type <- match.arg(type)
  sn <- colnames(structure)
  sn <- sn[grep("\\_l\\d{1}$", sn)]
  if (type=="code") {
    tree <- structure |>
      mutate(pathString = paste("Root", !!!syms(sn), sep="//"),
             desc = labelled::to_character(.data[[sn[length(sn)]]])) |>
      data.tree::as.Node(pathDelimiter = "//")
  } else {
    tree <- structure |>
      mutate(across(all_of(sn), labelled::to_character),
             pathString = paste("Root", !!!syms(sn), sep="//")) |>
      data.tree::as.Node(pathDelimiter = "//")
  }
  return(tree) }

#' Unlabel
#' @description Removes the labels column vectors from a hierarchy data frame
#' @param structure A data.frame generated by get_
#' @returns A data.frame with separate columns for hierarchy codes and code descriptions
#' @export
#' @importFrom labelled to_character remove_labels
#' @importFrom dplyr mutate across all_of

unlabel <- function(structure) {
  sn <- colnames(structure)
  sn <- sn[grep("\\_l\\d{1}$", sn)]
  structure |>
    mutate(across(.cols=all_of(sn),
                  .fns=to_character,
                  .names="{.col}_desc"),
           across(.cols=all_of(sn),
                  .fns=remove_labels),
           .before=sn[1])
}

#' Flatten Tree
#' @description Converts a data.tree hierarchy object into a parent, child data frame.
#' @param tree an object of class `data.tree`
#' @param ... other attributes to output from the tree
#'
#' @returns A data.frame with columns:
#'  - `from` the parent path string
#'  - `to` the child path string
#'  - `level` the tree depth of the child, root = 1
#'  - `parentName` the name of the parent node
#'  - `name` the name of the child node
#' @export
#' @importFrom data.tree Get Set ToDataFrameNetwork

flatten_tree <- function(tree, ...) {
  stopifnot("Node" %in% class(tree))
  if (any(tree$Get(\(x) grepl("\\/", x$name)))) {
    tree$Set(parentName = tree$Get(\(x) x$parent$name))
    df <- ToDataFrameNetwork(tree, "level", "parentName", "name", ...)
    df <- within(df, { from = parentName; to = name
                        parentName = NULL; name = NULL })
  } else {
    df <- ToDataFrameNetwork(tree, "level", ...)
  }
  return(df) }


